image: centos

before_script:
- echo "Starting Gitlab-CI script"

stages:
- build
- deploy

build_job:
  stage: build
  script:
  - /builds/william/ngx_openresty-rpm-spec/BUILDME.sh buildauto

deploy_job:
  stage: deploy
  script:
  - /builds/william/ngx_openresty-rpm-spec/BUILDME.sh buildinstall


