#image: centos
image: ngxdev@repository.snappyvault.com:5000

before_script:
- echo "Starting Gitlab-CI script"

stages:
- build
- deploy
- test

build_job:
  stage: build
  script:
  - /builds/william/ngx_openresty-rpm-spec/BUILDME.sh buildauto

deploy_job:
  stage: deploy
  script:
  - /builds/william/ngx_openresty-rpm-spec/BUILDME.sh buildinstall

test_job:
  stage: test
  script:
  - /builds/william/ngx_openresty-rpm-spec/tests/check_web.sh http://localhost
