
image: centos

# Internal Lab image (centos + pre-requisites)
#image: registry.snappyvault.com:5000/ngxdev

before_script:
- echo "Starting Gitlab-CI script"

stages:
# - build
- deploy

# Note: Build stage covered by deploy stage.
# build_job:
#   stage: build
#   script:
#   - /builds/william/ngx_openresty-rpm-spec/BUILDME.sh buildauto

deploy_job:
  stage: deploy
  script:
  - /builds/william/ngx_openresty-rpm-spec/BUILDME.sh buildinstall
  - /opt/ngx_openresty/nginx/sbin/nginx
  - /builds/william/ngx_openresty-rpm-spec/tests/check_web.sh http://localhost

#
# END OF FILE
#
